name: ItemHuntPlugin
version: '1.0-SNAPSHOT'
main: weitma.itemHuntPlugin.ItemHuntPlugin
api-version: '1.21'
commands:
  startchallenge:
    description: Starts the challenge
    parameters:
      - dauer: time
      - anzahlSkipItems: int
    default: op
    permission: itemhuntplugin.startchallenge
  resetchallenge:
    description: Resets the challenge
    default: op
    permission: itemhuntplugin.resetchallenge
  results:
    description: Shows the results
    default: op
    permission: itemhuntplugin.results
  teams:
    description: Shows the teams
  skipitem:
    description: Skips item by admin
    default: op
    permission: itemhuntplugin.skipitem
  showcollecteditems:
    description: Shows the collected items
  giverocket:
    description: Gives a rocket
    default: op
    permission: itemhuntplugin.giverocket
  resetteams:
    description: Resets the teams
    default: op
    permission: itemhuntplugin.resetteams