name: ItemHuntPlugin
version: '1.0-SNAPSHOT'
main: weitma.itemHuntPlugin.ItemHuntPlugin
api-version: '1.21'
commands:
  startchallenge:
    description: Starts the challenge
    parameters:
      - dauer: time
      - anzahlSkipItems: int
    default: op
    permission: itemhuntplugin.startchallenge
  stopchallenge:
    description: Stops the challenge
    default: op
  results:
    description: Shows the results
    default: op
  teams:
    description: Shows the teams
    default: op
  skipitem:
    description: Skips item by admin
    default: op
  showcollecteditems:
    description: Shows the collected items
    default: op
  reset:
    description: Resets the challenge
    default: op